import type { Store } from "./types";

export const seed: Store = {
  categories: ["Круглые", "Квадратные", "Прямоугольные"],
  products: [
    {
      id: "aurora",
      title: "Aurora",
      category: "Круглые",
      description: "Круглое зеркало с мягкой фоновой LED-подсветкой и сенсорным выключателем.",
      size: "Ø 60 / 80 / 100 см",
      price: 18900,
      images: [],
      badge: "Хит",
      visible: true,
      order: 1,
    },
    {
      id: "lune",
      title: "Lune",
      category: "Круглые",
      description: "Круглое зеркало в тонкой металлической раме цвета матовой латуни.",
      size: "Ø 70 см",
      price: 22000,
      images: [],
      badge: "Новинка",
      visible: true,
      order: 2,
    },
    {
      id: "quadro",
      title: "Quadro",
      category: "Квадратные",
      description: "Квадратное зеркало с контурной подсветкой и мягко скруглёнными углами.",
      size: "60 × 60 см",
      price: 17900,
      images: [],
      badge: "",
      visible: true,
      order: 3,
    },
    {
      id: "halo",
      title: "Halo",
      category: "Квадратные",
      description: "Влагостойкое зеркало с подсветкой, функцией антизапотевания и диммером.",
      size: "70 × 70 см",
      price: 27400,
      images: [],
      badge: "",
      visible: true,
      order: 4,
    },
    {
      id: "linea",
      title: "Linea",
      category: "Прямоугольные",
      description: "Строгая геометрия и контурная подсветка с регулировкой тёплого и холодного света.",
      size: "60 × 90 см",
      price: 24500,
      images: [],
      badge: "",
      visible: true,
      order: 5,
    },
    {
      id: "arco",
      title: "Arco",
      category: "Прямоугольные",
      description: "Напольное зеркало в полный рост для гардеробной и спальни.",
      size: "80 × 180 см",
      price: 38900,
      images: [],
      badge: "",
      visible: true,
      order: 6,
    },
  ],
  links: {
    avito: "",
    telegram: "",
    yandexMarket: "",
    instagram: "",
    tiktok: "",
    phone: "",
  },
  soldCount: "500+",
};
